### ISSUE TITLE
Store `templates` in `SQLite` database

### ISSUE THREAD

**Issue by joshiayush** [joshiayush/inb#17]
# Description

Add `message templates` in `SQL` database. Currently it only supports `json` files lying around the code base; we need a more efficient way to store and fetch the `template messages` for customizing invitation request because the way we currently store template data will get ugly when the message template database will increase.

https://github.com/joshiayush/inb/blob/c0073b1e686abe42a1c3809a2dc92a08ff5e000e/inb/linkedin/message/templates.json#L1-L17

# Possible solutions

The above data should be moved to a SQLite database named `message_templates` inside the directory `db` in the top level directory, to do so follow the following steps:

1. Create a database with name `message_templates.db`.
2. Create the following table or extend it if you want to:
    ```SQL
    CREATE TABLE database_name.message_templates(
        Id CHAR(50) PRIMARY KEY NOT NULL,
        Template TEXT NOT NULL,
        CreatedAt DATETIME DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
    );
    ```

__All the database operations must be performed inside of the directory [`inb/database`](https://github.com/joshiayush/inb/tree/master/inb/database).__

**Comment by oneamanish** [comment]
see my pull req.
