### ISSUE TITLE
"Weak Network" error message

### ISSUE THREAD

**Issue by 3ruce** [joshiayush/inb#22]
The following command:

```shell
python3 ~/inb/inb/inb.py search --email "a@f.com" --password "R" --keyword "Team Building" --location "London" --title "Director" --message ~/message-ndp-1.txt limit 1
```

Returns the following error:

```shell
INFO:Checking network status
inb: Error: InternetNotConnectedException: Weak network found
```

This is on `Debian 11` running in an `LXD` container with `16GB` of RAM?

**Comment by 3ruce** [comment]
Instead of using ping as per this code

https://github.com/joshiayush/inb/blob/master/inb/lib/utils/net.py

Why not use wget or curl and download google.com's homepage and then delete the temp file to test the internet e.g.

```
wget -O inb-test-google-index.html google.com
rm inb-test-google-index.html
```

inb needs port 80/443 open while ping uses another, non-standard port

**Comment by 3ruce** [comment]
Here's the fix for the problem with pinging not being allowed when running `ping 8.8.8.8` and getting this error `ping: socket: Operation not permitted`, likely caused by using inb in an lxd container or similar...

>Find out where the ping package is.It might have a different location. On my Ubuntu 18.04 machine, it is in /bin. Use `type -a ping` to locate it. Next, verify that it is there and is owned by root and is permed 755 (or similar)

```
ls -lsa /bin/ping
sudo chmod 4711 /bin/ping
```

Verify that the fix worked 

```
ls -lsa /bin/ping
ping 8.8.8.8
ping 2600:3c01::f03c:92ff:fe3b:2efa
```
Via https://askubuntu.com/a/1189359

**Comment by joshiayush** [comment]
We need to replace the current `ping` function with the function `is_internet_alive()` defined below in order to make it platform independent. I guess `Python` socket will not have any issue with a `LXD` container.

https://github.com/joshiayush/inb/blob/57fe58db1fd2062adf9b115994a795774ad1717f/inb/lib/utils/net.py#L29-L52

# Possible solutions

```python
def is_internet_alive(host: str = '1.1.1.1', port: int = 53, timeout: int = 3) -> bool:
    """Check if Internet Connection is alive and external IP address is reachable.
    
    Args:
        host (string): 1.1.1.1 (DNS servver)
        port (integer): (53/tcp DNS Service).
        timeout (float): timeout in seconds.
    
    Returns:
        True (bool): if external IP address is reachable.
        False (bool): if external IP address is unreachable.
    """
    try:
        socket.setdefaulttimeout(timeout)
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host, port))
    except OSError as error:
        return False
    else:
        s.close()
    return True
```
