### ISSUE TITLE
Arm64 compatibility

### ISSUE THREAD

**Issue by 3ruce** [joshiayush/inb#41]
I got the app working before on Arm64... from memory I just needed to install chromium and copy it to the required location...

`sudo apt install python3-pip python3-setuptools git chromium` get's the dependencies for debian and then `sudo cp /usr/bin/chromedriver ~/inb/driver/chromedriver` gets an arm64 compatible chromedriver binary in place...

**Comment by joshiayush** [comment]
What issue were you having with the `chromedriver` which comes with the repository? Why did you need to install `chromium` for that?

**Comment by 3ruce** [comment]
I can't recall but it may have been a problem with Ubuntu installing chromeium via snap and then the path's not being correct... I don't know if that helps though?
