### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by ologbonowiwi** [joshiayush/inb#53]
Any chance of us setting up the project with docker instead of manually download and installing with Python?

**Comment by joshiayush** [comment]
Yes it is a good idea to package up **inb**, I'm always open to the idea of accepting a PR packaging up **inb** so if you want please send me a PR.

**Comment by ologbonowiwi** [comment]
I'll be happy to handle this. 

I have a little blocker cause I can't access GitHub on my computer (it's a network problem, I'll be able to fix it in the middle of the week).

Also, I'm not highly experienced with Python, but feel free to assign this issue to me, and I'll do my best to solve it. 😁

**Comment by ologbonowiwi** [comment]
Hey @joshiayush, what's the Python version that you're running at?

**Comment by joshiayush** [comment]
Python 3.8

**Comment by joshiayush** [comment]
@ologbonowiwi Are you working on this? Because a few people wants to see it packaged up...

**Comment by ologbonowiwi** [comment]
Yeah, @joshiayush, I was having some issues with the Docker version, but it seems that with 3.8, it's working now.

By this week or so, I'll create the pull request.

**Comment by ologbonowiwi** [comment]
PR created with the Dockerfile.

IDK if you'll push this image to the Docker hub or anything like that, but if not, we can close this issue after your review

**Comment by joshiayush** [comment]
Resolved in 0043a73
