### ISSUE TITLE
Change primary branch from `master` to `main`

### ISSUE THREAD

**Issue by ologbonowiwi** [joshiayush/inb#54]
There are [known issues](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main) that seem to be problematic (resuming the whole history if the branch is `master`; all others are _**enslaved branches**_).

If the name is `main`, all other branches would be _**side branches**_ instead of _**enslaved branches**_. Can you fix that?

**Comment by joshiayush** [comment]
Renamed to `main` :+1:
