### ISSUE TITLE
Building image from Docker 

### ISSUE THREAD

**Issue by rawathemant246** [joshiayush/inb#64]
when i'm building the image from the readme file it is giving me error!

[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => CANCELED [internal] load .dockerignore                                                                         0.0s
 => => transferring context:                                                                                       0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2042251597/Dockerfile: no such file or directory

**Comment by joshiayush** [comment]
Using docker isn't recommended yet on devices other than the tested ones. @ologbonowiwi added the `Dockerfile` to the project, he must know the bug.

**Comment by ologbonowiwi** [comment]
@rawathemant246 most likely this is Windows related. 

I would say to you to try building it with WSL rather than build the image on Windows.

**Comment by rawathemant246** [comment]
@ologbonowiwi  thanks i'll check it
