### ISSUE TITLE
inb.py not providing any output

### ISSUE THREAD

**Issue by rawathemant246** [joshiayush/inb#65]
i have cloned the repo in my local and followed the instruction  when i run this script 

inb.py search --email xxxxx@gmail.com --password xxxx --keyword 'Software developer' --refresh-cookies 

simply it provides the output in the terminal like this 

Warning: 'email' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'password' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'keyword' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'refresh-cookies' is not in the list of known options, but still passed to Electron/Chromium.

kindly reslove the issue

**Comment by joshiayush** [comment]
You mean running the following command only shows that output and sends no connection request from your side?

```shell
inb.py search --email [xxxxx@gmail.com](mailto:xxxxx@gmail.com) --password xxxx --keyword 'Software developer' --refresh-cookies
```

**Comment by joshiayush** [comment]
Closing as stale!
